lib: [
  "_build/install/default/lib/visitors-cleanroom/META"
  "_build/install/default/lib/visitors-cleanroom/dune-package"
  "_build/install/default/lib/visitors-cleanroom/opam"
  "_build/install/default/lib/visitors-cleanroom/ppx/Visitors.ml" {"ppx/Visitors.ml"}
  "_build/install/default/lib/visitors-cleanroom/ppx/Visitors.mli" {"ppx/Visitors.mli"}
  "_build/install/default/lib/visitors-cleanroom/ppx/VisitorsAnalysis.ml" {"ppx/VisitorsAnalysis.ml"}
  "_build/install/default/lib/visitors-cleanroom/ppx/VisitorsCompatibility.ml" {"ppx/VisitorsCompatibility.ml"}
  "_build/install/default/lib/visitors-cleanroom/ppx/VisitorsGeneration.ml" {"ppx/VisitorsGeneration.ml"}
  "_build/install/default/lib/visitors-cleanroom/ppx/VisitorsList.ml" {"ppx/VisitorsList.ml"}
  "_build/install/default/lib/visitors-cleanroom/ppx/VisitorsPlugin.ml" {"ppx/VisitorsPlugin.ml"}
  "_build/install/default/lib/visitors-cleanroom/ppx/VisitorsSettings.ml" {"ppx/VisitorsSettings.ml"}
  "_build/install/default/lib/visitors-cleanroom/ppx/VisitorsString.ml" {"ppx/VisitorsString.ml"}
  "_build/install/default/lib/visitors-cleanroom/ppx/ppx_deriving_visitors.a" {"ppx/ppx_deriving_visitors.a"}
  "_build/install/default/lib/visitors-cleanroom/ppx/ppx_deriving_visitors.cma" {"ppx/ppx_deriving_visitors.cma"}
  "_build/install/default/lib/visitors-cleanroom/ppx/ppx_deriving_visitors.cmi" {"ppx/ppx_deriving_visitors.cmi"}
  "_build/install/default/lib/visitors-cleanroom/ppx/ppx_deriving_visitors.cmt" {"ppx/ppx_deriving_visitors.cmt"}
  "_build/install/default/lib/visitors-cleanroom/ppx/ppx_deriving_visitors.cmx" {"ppx/ppx_deriving_visitors.cmx"}
  "_build/install/default/lib/visitors-cleanroom/ppx/ppx_deriving_visitors.cmxa" {"ppx/ppx_deriving_visitors.cmxa"}
  "_build/install/default/lib/visitors-cleanroom/ppx/ppx_deriving_visitors.ml" {"ppx/ppx_deriving_visitors.ml"}
  "_build/install/default/lib/visitors-cleanroom/ppx/ppx_deriving_visitors__Visitors.cmi" {"ppx/ppx_deriving_visitors__Visitors.cmi"}
  "_build/install/default/lib/visitors-cleanroom/ppx/ppx_deriving_visitors__Visitors.cmt" {"ppx/ppx_deriving_visitors__Visitors.cmt"}
  "_build/install/default/lib/visitors-cleanroom/ppx/ppx_deriving_visitors__Visitors.cmti" {"ppx/ppx_deriving_visitors__Visitors.cmti"}
  "_build/install/default/lib/visitors-cleanroom/ppx/ppx_deriving_visitors__Visitors.cmx" {"ppx/ppx_deriving_visitors__Visitors.cmx"}
  "_build/install/default/lib/visitors-cleanroom/ppx/ppx_deriving_visitors__VisitorsAnalysis.cmi" {"ppx/ppx_deriving_visitors__VisitorsAnalysis.cmi"}
  "_build/install/default/lib/visitors-cleanroom/ppx/ppx_deriving_visitors__VisitorsAnalysis.cmt" {"ppx/ppx_deriving_visitors__VisitorsAnalysis.cmt"}
  "_build/install/default/lib/visitors-cleanroom/ppx/ppx_deriving_visitors__VisitorsAnalysis.cmx" {"ppx/ppx_deriving_visitors__VisitorsAnalysis.cmx"}
  "_build/install/default/lib/visitors-cleanroom/ppx/ppx_deriving_visitors__VisitorsCompatibility.cmi" {"ppx/ppx_deriving_visitors__VisitorsCompatibility.cmi"}
  "_build/install/default/lib/visitors-cleanroom/ppx/ppx_deriving_visitors__VisitorsCompatibility.cmt" {"ppx/ppx_deriving_visitors__VisitorsCompatibility.cmt"}
  "_build/install/default/lib/visitors-cleanroom/ppx/ppx_deriving_visitors__VisitorsCompatibility.cmx" {"ppx/ppx_deriving_visitors__VisitorsCompatibility.cmx"}
  "_build/install/default/lib/visitors-cleanroom/ppx/ppx_deriving_visitors__VisitorsGeneration.cmi" {"ppx/ppx_deriving_visitors__VisitorsGeneration.cmi"}
  "_build/install/default/lib/visitors-cleanroom/ppx/ppx_deriving_visitors__VisitorsGeneration.cmt" {"ppx/ppx_deriving_visitors__VisitorsGeneration.cmt"}
  "_build/install/default/lib/visitors-cleanroom/ppx/ppx_deriving_visitors__VisitorsGeneration.cmx" {"ppx/ppx_deriving_visitors__VisitorsGeneration.cmx"}
  "_build/install/default/lib/visitors-cleanroom/ppx/ppx_deriving_visitors__VisitorsList.cmi" {"ppx/ppx_deriving_visitors__VisitorsList.cmi"}
  "_build/install/default/lib/visitors-cleanroom/ppx/ppx_deriving_visitors__VisitorsList.cmt" {"ppx/ppx_deriving_visitors__VisitorsList.cmt"}
  "_build/install/default/lib/visitors-cleanroom/ppx/ppx_deriving_visitors__VisitorsList.cmx" {"ppx/ppx_deriving_visitors__VisitorsList.cmx"}
  "_build/install/default/lib/visitors-cleanroom/ppx/ppx_deriving_visitors__VisitorsPlugin.cmi" {"ppx/ppx_deriving_visitors__VisitorsPlugin.cmi"}
  "_build/install/default/lib/visitors-cleanroom/ppx/ppx_deriving_visitors__VisitorsPlugin.cmt" {"ppx/ppx_deriving_visitors__VisitorsPlugin.cmt"}
  "_build/install/default/lib/visitors-cleanroom/ppx/ppx_deriving_visitors__VisitorsPlugin.cmx" {"ppx/ppx_deriving_visitors__VisitorsPlugin.cmx"}
  "_build/install/default/lib/visitors-cleanroom/ppx/ppx_deriving_visitors__VisitorsSettings.cmi" {"ppx/ppx_deriving_visitors__VisitorsSettings.cmi"}
  "_build/install/default/lib/visitors-cleanroom/ppx/ppx_deriving_visitors__VisitorsSettings.cmt" {"ppx/ppx_deriving_visitors__VisitorsSettings.cmt"}
  "_build/install/default/lib/visitors-cleanroom/ppx/ppx_deriving_visitors__VisitorsSettings.cmx" {"ppx/ppx_deriving_visitors__VisitorsSettings.cmx"}
  "_build/install/default/lib/visitors-cleanroom/ppx/ppx_deriving_visitors__VisitorsString.cmi" {"ppx/ppx_deriving_visitors__VisitorsString.cmi"}
  "_build/install/default/lib/visitors-cleanroom/ppx/ppx_deriving_visitors__VisitorsString.cmt" {"ppx/ppx_deriving_visitors__VisitorsString.cmt"}
  "_build/install/default/lib/visitors-cleanroom/ppx/ppx_deriving_visitors__VisitorsString.cmx" {"ppx/ppx_deriving_visitors__VisitorsString.cmx"}
  "_build/install/default/lib/visitors-cleanroom/visitorsRuntime.a"
  "_build/install/default/lib/visitors-cleanroom/visitorsRuntime.cma"
  "_build/install/default/lib/visitors-cleanroom/visitorsRuntime.cmi"
  "_build/install/default/lib/visitors-cleanroom/visitorsRuntime.cmt"
  "_build/install/default/lib/visitors-cleanroom/visitorsRuntime.cmti"
  "_build/install/default/lib/visitors-cleanroom/visitorsRuntime.cmx"
  "_build/install/default/lib/visitors-cleanroom/visitorsRuntime.cmxa"
  "_build/install/default/lib/visitors-cleanroom/visitorsRuntime.ml"
  "_build/install/default/lib/visitors-cleanroom/visitorsRuntime.mli"
]
libexec: [
  "_build/install/default/lib/visitors-cleanroom/ppx/ppx_deriving_visitors.cmxs" {"ppx/ppx_deriving_visitors.cmxs"}
  "_build/install/default/lib/visitors-cleanroom/visitorsRuntime.cmxs"
]
doc: [
  "_build/install/default/doc/visitors-cleanroom/README.md"
]
