name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ocaml-compiler: ['5.3']
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          submodules: recursive

      - uses: ocaml/setup-ocaml@15d660006c1d3110d77c34b7faa3bddefe8b82f0 # v3.7.0
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: Install dependencies
        run: |
          opam install . --deps-only --with-test
          opam install visitors qcheck-core qcheck-alcotest alcotest bechamel

      - name: Build
        run: opam exec -- dune build

      - name: Build (package mode)
        run: opam exec -- dune build -p visitors-cleanroom

      - name: Test
        run: opam exec -- dune test --force
